//
//  MainInteractor.swift
//  MusicLibrary
//
//  Created by Fachri Work on 12/7/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func loadAlbums()
}

protocol MainDataStore {
    //var name: String { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func loadAlbums() {
        let albums = LibraryAPI.shared.getAlbums()
        
        let response = Main.Albums.Response(albums: albums)
        presenter?.presentAlbums(response: response)
    }
}
