//
//  MainWorker.swift
//  MusicLibrary
//
//  Created by Fachri Work on 12/7/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker {

  func doSomeWork() {
  
  }
}
