//
//  MainPresenter.swift
//  MusicLibrary
//
//  Created by Fachri Work on 12/7/17.
//  Copyright (c) 2017 Decadev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentAlbums(response: Main.Albums.Response)
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentAlbums(response: Main.Albums.Response) {
        let viewModel = Main.Albums.ViewModel(albums: response.albums)
        viewController?.displayAlbums(viewModel: viewModel)
    }
}
